{% set name = "plothist" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plothist-{{ version }}.tar.gz
  sha256: 21a67583c7c07734d3295ae80eb382cca6070ad556f4221a6612870793ff51d3

build:
  entry_points:
    - install_latin_modern_fonts = plothist.scripts.install_latin_modern_fonts:install_latin_modern_fonts
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - boost-histogram >=1.4.0,<1.5.dev0
    - numpy >=1.14.5
    - matplotlib-base >=3.0
    - pyyaml >=5.3.1
    - scipy >=1.6.0
    - requests >=2.25.0

test:
  imports:
    - plothist
  commands:
    - pip check
    # On macOS need /Users/<username>/Library/Fonts
    - install_latin_modern_fonts  # [linux]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cyrraz/plothist
  summary: Plot histograms in a scalable way and a beautiful style.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://plothist.readthedocs.io/
  dev_url: https://github.com/cyrraz/plothist

extra:
  recipe-maintainers:
    - 0ctagon
