{% set name = "plothist" %}
{% set version = "1.5.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plothist-{{ version }}.tar.gz
  sha256: 46419a2e551988527956ed9d19879bb129558511d9910908e0aa7d22fa6987cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - boost-histogram >=1.4.0,<1.5.dev0
    - numpy >=1.14.5
    - matplotlib-base >=3.0
    - pyyaml >=5.3.1
    - scipy >=1.6.0
    - requests >=2.25.0
    - plothist_utils >=0.0.1

test:
  imports:
    - plothist
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cyrraz/plothist
  summary: Plot histograms in a scalable way and a beautiful style.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://plothist.readthedocs.io/
  dev_url: https://github.com/cyrraz/plothist

extra:
  recipe-maintainers:
    - 0ctagon
